### PR TITLE
add a window to configure some of the Plot2d widget options

### PR DESCRIPTION
**Pull request by jcmonteiro**
Through this window one may alter the settings shown below
preferences
The window is opened by right-clicking the plot area and selecting "Preferences".

Each Plot2d instance has its own preferences window. Global settings are loaded when the plot is created and might be reloaded by clicking "Load" or overwritten by clicking "Save". The buttons "Apply" and "Ok" only change the current instance settings.

### CODE REVIEW

**Comment by doudou** [comment]
This is great, Joao. Thanks.

Would you mind maybe implementing tests for it ? The tests are interactive (you basically do stuff and tell the human to either do things himself or check that things look like what they should).

**Comment by jcmonteiro** [comment]
Yeah, sure. I'll have a look at what you did for the clear button.

**Comment by jcmonteiro** [comment]
I have also added an "Autosize" menu action. It's one commit ahead of plot2d_preferences at https://github.com/jcmonteiro/gui-vizkit/commit/1ab1e754d836221fb3d8fe327827842b8105f30d. Should I add it here or in a separate PR?

**Comment by doudou** [comment]
Just add it here.

**Comment by doudou** [comment]
*Really* cool. Thanks a lot.

**Pull request merged**
